# Generated by Django 5.1 on 2026-04-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('biyografi', models.TextField(blank=True)),
                ('dogum_yili', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yayin_yili', models.PositiveIntegerField()),
                ('sayfa_sayisi', models.PositiveIntegerField()),
                ('aciklama', models.TextField(blank=True)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitaplar', to='books.kategori')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitaplar', to='books.yazar')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
