# Generated by Django 5.1 on 2026-04-07 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OduncAlma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odunc_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('son_iade_tarihi', models.DateTimeField()),
                ('teslim_tarihi', models.DateTimeField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odunc_islemleri', to='books.kitap')),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odunc_islemleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ödünç Alma',
                'verbose_name_plural': 'Ödünç Alma İşlemleri',
                'ordering': ['-odunc_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='UyeProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('adres', models.TextField(blank=True)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üye Profili',
                'verbose_name_plural': 'Üye Profilleri',
            },
        ),
    ]
