# Generated by Django 5.1 on 2026-04-07 20:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_oduncalma_uyeprofil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitapDegerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.PositiveSmallIntegerField(choices=[(1, '1 Yildiz'), (2, '2 Yildiz'), (3, '3 Yildiz'), (4, '4 Yildiz'), (5, '5 Yildiz')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('yorum', models.TextField(blank=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='books.kitap')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitap Değerlendirmesi',
                'verbose_name_plural': 'Kitap Değerlendirmeleri',
                'ordering': ['-olusturma_tarihi'],
                'constraints': [models.UniqueConstraint(fields=('kullanici', 'kitap'), name='unique_kullanici_kitap_degerlendirme')],
            },
        ),
    ]
